server:
  port: 8000

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: currency-exchange-service
  profiles:
    active: dev
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true