server:
  port: 8000

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: currency-exchange-service
  profiles:
    active: dev
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  sleuth:
    sampler:
      probabililty: 1.0 #Percentage of messages sent for tracing, in this case, 100% of them

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  retry:
    instances:
      sample-api:
        maxRetryAttempts: 5
        waitDuration: 2s
