server:
  port: 8100

spring:
  application:
    name: currency-conversion-service
  cloud:
    config:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka