server:
  port: 8100

spring:
  application:
    name: currency-conversion-service
  cloud:
    config:
      enabled: false
  sleuth:
    sampler:
      probabililty: 1.0 #Percentage of messages sent for tracing, in this case, 100% of them

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka